
# gdb config file for management additional gdb config files

if $USE_CONFIG_SETTINGS     == 1
	source ~/.gdb/config.settings
end
if $USE_CONFIG_FUNCTIONS    == 1
	source ~/.gdb/config.functions
end
if $USE_CONFIG_PYTHON       == 1
	source ~/.gdb/config.python.3
end
if $USE_CONFIG_REVERSEPUTAS == 1
	source ~/.gdb/config.reverseputas.20160403
end
if $USE_CONFIG_ALIASES      == 1
	source ~/.gdb/config.aliases
end

